### ISSUE TITLE
program won't run

### ISSUE THREAD

**Issue by matthewboman** [michaelcheng429/meanstacktutorial#5]
when I try node server or node server.js I get this error:

```
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/crash/js/node/LCT/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
/home/crash/js/node/LCT/node_modules/mongojs/index.js:662
    var p = Proxy.create({
              ^

TypeError: Proxy.create is not a function
    at connect (/home/crash/js/node/LCT/node_modules/mongojs/index.js:662:19)
    at Object.<anonymous> (/home/crash/js/node/LCT/server.js:6:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3
```

**Comment by deepakapte06** [comment]
i get the same error. :(

**Comment by snowfake** [comment]
In package.json change to "mongojs": "*" to get lastest version.

After: execute "npm update"

Worked to me..

**Comment by ghiitais** [comment]
@snowfake  Thank you !
